version: '3.3'
services:
  db:
    image: mysql:8.0
    ports:
      - "33306:3306"
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
