name: PHPStan

on:
  push:
    paths:
      - "**.php"
      - "phpstan.neon.dist"
  pull_request:
    branches: [master]

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: "laravel"
      DB_HOST: "127.0.0.1"
      DB_PORT: "3306"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"

    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE laravel' -uroot -proot

      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
